#!/usr/bin/env python3
"""Generate docs/AUDIO_MAP.md (PIGGY FIREFIGHTERS, family tool LUCKY audio_map_lucky.py adapted 2026-09-25): every cue id ->
game moment -> bus -> length -> gain -> what it sounds like (the prompt / plan it is drawn from, or how it is derived) ->
seam / donor id it replaces -> build notes (key-fit, snap, hybrid, hook pickup, re-master). Works on the ROSTER before any
draw (status planned: lengths are planned) and after the build (status built: measured). Source of truth: audio/cues.json +
audio/tools/prompts.json + plans.json.   usage: python3 audio/tools/audio_map.py"""
import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import kit as K
ROOT = K.ROOT
doc = json.load(open(f'{ROOT}/audio/cues.json')); cues = doc['cues']
P = json.load(open(f'{K.TOOLS}/prompts.json')); PL = json.load(open(f'{K.TOOLS}/plans.json'))


def short(t, n=150):
    t = t.replace('|', '/'); return t if len(t) <= n else t[:n - 1].rsplit(' ', 1)[0] + ' …'


def sounds(c):
    cid = c['id']; d = c.get('derive') or {}; src = c.get('source')
    if c['bus'] == 'music':
        pn = (c.get('build') or {}).get('source', src or '').rsplit('__', 1)[0]; pl = PL.get(pn, {})
        return short(f"{c.get('bars')}-bar loop @ {c.get('tempoBpm')} BPM: " + (pl.get('positive') or [''])[0])
    if src in P: return short(P[src]['prompt'])
    op = d.get('op'); frm = d.get('from')
    if op == 'turbo': return f"{frm} time-scaled x{d.get('timeScale')} (turbo, pitch kept)"
    if op == 'ladder': return f"{frm} pitched +{d.get('semis')} st (tonic ladder C D E G A)"
    if op == 'ladder-resample': return f"{frm} resampled +{d.get('semis')} st (count-up ladder)"
    if op == 'hybrid-chord' and frm: return f"drawn bell strike ({short(P[frm]['prompt'], 60)}) + synthesised chime chord {d.get('chord')}"
    if op == 'hybrid-ping': return f"drawn {frm} + tuned ping MIDI {d.get('note')}"
    if op == 'hybrid-ping-ladder': return f"tuned C5 blip + drawn click ({short(P[frm]['prompt'], 60)})"
    if op == 'snap-ladder': return f"{frm} (snapped brass ta-da) shifted to the rung's held note"
    if op == 'pitch': return f"{frm} pitched +{d.get('semis')} st"
    if op == 'stack': return f"stack of {', '.join(d.get('of', []))} (one merged stop)"
    return op or ''


def notes(c):
    B = c.get('build') or {}; n = []
    k = B.get('key') or {}
    if k.get('semis'): n.append(f"key-fit {k['semis']:+.2f} st")
    if (B.get('pitch') or {}).get('op') == 'pitch-snapped': n.append(f"snap {B['pitch']['semis']:+.2f} st -> {B['pitch']['targetNote']}")
    if B.get('tonal'): n.append(B['tonal'].get('op', 'hybrid'))
    if (B.get('hook') or {}).get('pickup') is True: n.append('hook pickup')
    if B.get('hook') and isinstance(B['hook'], dict) and B['hook'].get('colour'): n.append(f"hook {B['hook']['colour']} bars {[b + 1 for b in B['hook']['bars']]}")
    if B.get('remaster'): n.append(f"re-mastered +{B['remaster']['raised_dB']} dB")
    if c.get('duck'): n.append('duck ' + ', '.join(f'{a} {b}' for a, b in c['duck'].items()))
    if c.get('gate'): n.append('gate: ' + c['gate'])
    return '; '.join(n)


built = sum(1 for c in cues if c.get('status') == 'built')
rows = []
for c in cues:
    seam = c.get('seam', '') + (f" (replaces `{c['replaces']}`)" if c.get('replaces') else '')
    ms = c.get('durationMs'); ms = f"{ms:g}" + ('' if c.get('status') == 'built' else ' (planned)')
    rows.append((f"`{c['id']}`", c.get('event', ''), c['bus'], 'loop' if c.get('loop') else '', ms, c.get('gain'), sounds(c), seam, notes(c)))
g = doc['grid']
os.makedirs(f'{ROOT}/docs', exist_ok=True)
with open(f'{ROOT}/docs/AUDIO_MAP.md', 'w') as f:
    f.write('# PIGGY FIREFIGHTERS — audio map (generated)\n\n'
            'Generated by `audio/tools/audio_map.py` from `audio/cues.json` (the registry the client loads through the generated '
            '`apps/piggy_firefighters/src/game/audio/cueManifest.ts`), `audio/tools/prompts.json` and `audio/tools/plans.json`. '
            'Do not hand-edit: change `audio/tools/roster.py`, re-run it, then this. Direction and rules: `assets/SOUND_BIBLE.md`; '
            'pipeline: `audio/README.md`.\n\n'
            f"**{len(rows)} cue ids; {built} built, {len(rows) - built} planned.** Grid: base {g['tempoBpm']} BPM, bonus/rungs "
            f"{sorted(set(v for k, v in g['bonusBpm'].items() if v != g['tempoBpm']))} BPM, key {g['key']}, hook {g['hook']['notes']}. "
            'Gain = pre-duck cue trim from `audio/tools/mix.py` (1.0 until measured). `seam` = where the new id should be played; '
            '`replaces` = the donor id the ported runtime still plays there (the runtime seam is a later frontend task). '
            + ('**Nobody has listened to any of this yet.**' if built else '**Roster only: no sound has been drawn yet.**') + '\n\n')
    f.write('## Rules every cue follows\n\n' + '\n'.join(f'- {r}' for r in doc['mix']['rules']) + '\n\n')
    f.write('## Transitions\n\n' + '\n'.join(f'- **{k}**: {v}' for k, v in doc['transitions'].items()) + '\n\n')
    f.write('## Cues\n\n| id | moment | bus | loop | ms | gain | sounds like | seam | notes |\n|---|---|---|---|---|---|---|---|---|\n')
    for r in rows: f.write('| ' + ' | '.join(str(v) for v in r) + ' |\n')
print('wrote docs/AUDIO_MAP.md', len(rows), 'rows', f'({built} built)')
