/**
 * GENERATED by tools/art/gen_art_meta.mjs from the art lane's meta JSON under static/assets (frame.meta.json,
 * cells.meta.json, rooms.meta.json, props.meta.json, winrungs/signs/flat_manifest.json, maxwin/manifest.json, the two
 * symbol manifests). Do not edit: re-run the script after a derive tool changes a rect; qa/gate checks it is in sync.
 * game/artMeta.ts is the typed reader.
 */
export const frameMeta = {
	"w": 1497,
	"h": 946,
	"open_px": {
		"x0": 212,
		"x1": 1279,
		"y0": 178,
		"y1": 761
	},
	"top_tile": [
		340,
		36,
		487,
		154
	],
	"rail_period_px": 241
} as const;

export const cellsMeta = {
	"frames": {
		"plain": {
			"file": "cell_frame_plain.webp",
			"size": [
				384,
				384
			],
			"hole": [
				0.1589,
				0.1693,
				0.8411,
				0.8385
			]
		},
		"win": {
			"file": "cell_frame_win.webp",
			"size": [
				384,
				384
			],
			"hole": [
				0.1562,
				0.1693,
				0.8411,
				0.8385
			]
		},
		"locked": {
			"file": "cell_frame_locked.webp",
			"size": [
				384,
				384
			],
			"hole": [
				0.1693,
				0.1745,
				0.8307,
				0.8229
			]
		}
	},
	"line_plate": {
		"file": "line_plate.webp",
		"size": [
			307,
			291
		]
	}
} as const;

export const roomsMeta = {
	"states": {
		"roaring": 2,
		"smouldering": 1,
		"safe": 0
	},
	"facade": {
		"files": {
			"rescue": "block_facade.webp",
			"inferno": "block_facade_inferno.webp"
		},
		"box": [
			119,
			108,
			1417,
			484
		]
	},
	"pitch_px": 233.9,
	"rooms": [
		{
			"reel": 0,
			"size": [
				234,
				390
			],
			"box_in_facade": [
				63,
				-24,
				297,
				366
			],
			"window_in_facade": [
				92,
				123,
				268,
				296
			],
			"files": {
				"roaring": "room_0_roaring.webp",
				"smouldering": "room_0_smouldering.webp",
				"safe": "room_0_safe.webp",
				"inferno_roaring": "room_0_inferno_roaring.webp",
				"inferno_smouldering": "room_0_inferno_smouldering.webp",
				"inferno_safe": "room_0_inferno_safe.webp"
			}
		},
		{
			"reel": 1,
			"size": [
				233,
				390
			],
			"box_in_facade": [
				301,
				-24,
				534,
				366
			],
			"window_in_facade": [
				329,
				124,
				506,
				296
			],
			"files": {
				"roaring": "room_1_roaring.webp",
				"smouldering": "room_1_smouldering.webp",
				"safe": "room_1_safe.webp",
				"inferno_roaring": "room_1_inferno_roaring.webp",
				"inferno_smouldering": "room_1_inferno_smouldering.webp",
				"inferno_safe": "room_1_inferno_safe.webp"
			}
		},
		{
			"reel": 2,
			"size": [
				234,
				390
			],
			"box_in_facade": [
				532,
				-24,
				766,
				366
			],
			"window_in_facade": [
				561,
				124,
				737,
				296
			],
			"files": {
				"roaring": "room_2_roaring.webp",
				"smouldering": "room_2_smouldering.webp",
				"safe": "room_2_safe.webp",
				"inferno_roaring": "room_2_inferno_roaring.webp",
				"inferno_smouldering": "room_2_inferno_smouldering.webp",
				"inferno_safe": "room_2_inferno_safe.webp"
			}
		},
		{
			"reel": 3,
			"size": [
				233,
				390
			],
			"box_in_facade": [
				765,
				-24,
				998,
				366
			],
			"window_in_facade": [
				793,
				124,
				970,
				296
			],
			"files": {
				"roaring": "room_3_roaring.webp",
				"smouldering": "room_3_smouldering.webp",
				"safe": "room_3_safe.webp",
				"inferno_roaring": "room_3_inferno_roaring.webp",
				"inferno_smouldering": "room_3_inferno_smouldering.webp",
				"inferno_safe": "room_3_inferno_safe.webp"
			}
		},
		{
			"reel": 4,
			"size": [
				233,
				390
			],
			"box_in_facade": [
				999,
				-24,
				1232,
				366
			],
			"window_in_facade": [
				1027,
				124,
				1204,
				296
			],
			"files": {
				"roaring": "room_4_roaring.webp",
				"smouldering": "room_4_smouldering.webp",
				"safe": "room_4_safe.webp",
				"inferno_roaring": "room_4_inferno_roaring.webp",
				"inferno_smouldering": "room_4_inferno_smouldering.webp",
				"inferno_safe": "room_4_inferno_safe.webp"
			}
		}
	]
} as const;

export const propsMeta = {
	"props": {
		"ladder_segment": {
			"file": "ladder_segment.webp",
			"size": [
				299,
				530
			],
			"rung_period_px": 176.8,
			"rail_span_px": [
				2,
				297
			]
		},
		"ladder_top": {
			"file": "ladder_top.webp",
			"size": [
				357,
				430
			]
		},
		"jump_sheet": {
			"file": "jump_sheet.webp",
			"size": [
				716,
				389
			]
		},
		"badge_blank": {
			"file": "badge_blank.webp",
			"size": [
				341,
				335
			]
		},
		"spins_plate_blank": {
			"file": "spins_plate_blank.webp",
			"size": [
				567,
				216
			]
		},
		"hose_nozzle": {
			"file": "hose_nozzle.webp",
			"size": [
				702,
				349
			]
		},
		"hose_segment": {
			"file": "hose_segment.webp",
			"size": [
				527,
				162
			]
		},
		"steam_puff": {
			"file": "steam_puff.webp",
			"size": [
				304,
				318
			]
		},
		"water_jet": {
			"file": "water_jet.webp",
			"size": [
				713,
				523
			]
		},
		"water_splash": {
			"file": "water_splash.webp",
			"size": [
				518,
				371
			]
		}
	}
} as const;

export const signsMeta = {
	"big": {
		"file": "signs/big.webp",
		"w": 1200,
		"h": 728,
		"plank": [
			600,
			634.2,
			901.7,
			187.2
		],
		"board": [
			600,
			338.3,
			1139.4,
			364.3
		],
		"title_centre": [
			600,
			338
		]
	},
	"huge": {
		"file": "signs/huge.webp",
		"w": 1200,
		"h": 728,
		"plank": [
			600,
			634.2,
			901.7,
			187.2
		],
		"board": [
			600,
			338.3,
			1139.4,
			364.3
		],
		"title_centre": [
			600,
			338
		]
	},
	"mega": {
		"file": "signs/mega.webp",
		"w": 1200,
		"h": 728,
		"plank": [
			600,
			634.2,
			901.7,
			187.2
		],
		"board": [
			600,
			338.3,
			1139.4,
			364.3
		],
		"title_centre": [
			600,
			338
		]
	},
	"epic": {
		"file": "signs/epic.webp",
		"w": 1200,
		"h": 728,
		"plank": [
			600,
			634.2,
			901.7,
			187.2
		],
		"board": [
			600,
			338.3,
			1139.4,
			364.3
		],
		"title_centre": [
			600,
			378.5
		]
	},
	"max": {
		"file": "signs/max.webp",
		"w": 1200,
		"h": 728,
		"plank": [
			600,
			634.2,
			901.7,
			187.2
		],
		"board": [
			600,
			338.3,
			1139.4,
			364.3
		],
		"title_centre": [
			600,
			389
		]
	}
} as const;

export const maxwinMeta = {
	"files": {
		"landscape": "max_win_card_16x9.webp",
		"portrait": "max_win_card_portrait.webp"
	},
	"size": {
		"landscape": [
			1600,
			900
		],
		"portrait": [
			900,
			1400
		]
	},
	"titleSafeArea": {
		"landscape": {
			"x": 0.04,
			"y": 0.14,
			"w": 0.36,
			"h": 0.72
		},
		"portrait": {
			"x": 0.1,
			"y": 0.04,
			"w": 0.8,
			"h": 0.24
		}
	}
} as const;

export const symbolsMeta = {
	"tile": 384,
	"pad": 0.068,
	"wild_badge": {
		"sym_W": {
			"x": 120,
			"y": 209,
			"w": 143,
			"h": 129
		},
		"sym_W_BLAZE": {
			"x": 122,
			"y": 211,
			"w": 140,
			"h": 127
		},
		"sym_W_b": {
			"x": 124,
			"y": 200,
			"w": 135,
			"h": 133
		}
	}
} as const;

export const symbolsTallMeta = {
	"tile": [
		384,
		500
	],
	"fill_w": 0.86,
	"wild_badge": {
		"symT_W": {
			"x": 123,
			"y": 242,
			"w": 137,
			"h": 142
		},
		"symT_W_BLAZE": {
			"x": 125,
			"y": 245,
			"w": 137,
			"h": 142
		},
		"symT_W_b": {
			"x": 126,
			"y": 234,
			"w": 132,
			"h": 139
		}
	}
} as const;
