// GENERATED by tools/perf/derive_lod_textures.py — do not edit by hand.
// Files under static/assets/lod/<path> exist at LOD_SCALE of the original static/assets/<path>.
export const LOD_SCALE = 0.625;
export const LOD_FILES: ReadonlySet<string> = new Set([
	'buycards/inferno.webp',
	'environment/backdraft_landscape.webp',
	'environment/backdraft_portrait.webp',
	'environment/base_landscape.webp',
	'environment/base_portrait.webp',
	'environment/inferno_landscape.webp',
	'environment/inferno_portrait.webp',
	'environment/rescue_landscape.webp',
	'environment/rescue_portrait.webp',
	'maxwin/max_win_card_16x9.webp',
	'maxwin/max_win_card_portrait.webp',
	'splash/card_alarm.webp',
	'splash/card_backdraft.webp',
	'splash/card_rescue.webp',
	'winrungs/signs/big.webp',
	'winrungs/signs/epic.webp',
	'winrungs/signs/huge.webp',
	'winrungs/signs/max.webp',
	'winrungs/signs/mega.webp',
]);
