import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
process.env.PLAYWRIGHT_BROWSERS_PATH ??= '/opt/pw-browsers';
const { chromium } = require('/opt/node22/lib/node_modules/playwright');
const ARGS = ['--mute-audio', '--autoplay-policy=no-user-gesture-required', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'];
const browser = await chromium.launch({ channel: 'chromium', args: ARGS });
const page = await (await browser.newContext({ viewport: { width: 1440, height: 900 } })).newPage();
const bad = [];
page.on('response', (r) => { if (r.status() >= 400) bad.push(`${r.status()} ${r.url()}`); });
page.on('console', (m) => { if (m.type() === 'error') bad.push(`console: ${m.text().slice(0, 200)}`); });
await page.goto(`http://127.0.0.1:3005/?sessionID=probe-${Date.now()}&rgs_url=127.0.0.1:3047&device=desktop`, { waitUntil: 'domcontentloaded' });
await page.waitForSelector('.splash .press', { timeout: 180000 });
await page.mouse.click(720, 450);
await page.waitForTimeout(8000);
console.log(JSON.stringify(bad, null, 1));
await browser.close();
