#!/usr/bin/env python3
"""Write art-src/animation/parts/INVENTORY.md from the files on disk + each rig's registration.json (free)."""
import hashlib
import json
import os

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
RIGS = ["pf_chief", "pf_rookie", "pf_dog", "pf_rescued"]
DESC = {
    "master": "full character, neutral three-quarter pose, feet on the common feet line (integer shift of the raw master)",
    "body_no_head_no_arms": "torso + legs + tail; neck stub and shoulder caps painted (registered)",
    "body_no_head_no_legs": "torso + collar; neck, shoulder/hip sockets and rump painted (registered)",
    "head_no_helmet": "head with face, ears (moustache on the chief); crown painted where the helmet was (registered)",
    "head": "head with face and ears, neck stub (registered)",
    "head_blank": "head base without eyes/brows/mouth/ears (snout kept) for layered faces (registered)",
    "helmet_only": "helmet with blank brass plate; navy lining painted under the brim (registered)",
    "arms_down": "both arms on one layer, shoulder caps painted (registered)",
    "arm_right": "character's right arm = image-left, near side (split of arms_down)",
    "arm_left": "character's left arm = image-right, far side (split of arms_down)",
    "arms_raised": "both arms raised (cheer), placed so each shoulder cap sits on the down arm's shoulder",
    "arm_right_raised": "raised right arm (split of arms_raised)",
    "arm_left_raised": "raised left arm (split of arms_raised)",
    "legs": "legs/boots on one layer, hip ends painted (registered)",
    "leg_right": "image-left leg (split of legs)",
    "leg_left": "image-right leg (split of legs)",
    "coat_tails": "coat skirt below the belt, lining painted, top edge tucks under the belt (registered)",
    "hands_sheet": "hand variants sheet (see pieces/)",
    "face_sheet": "eyes / brows / mouths (+ moustache, ears) sheet (see pieces/)",
    "props": "props sheet (see pieces/)",
    "parts_sheet": "ears, tail, jaw, jawless head, tongue sheet (see pieces/)",
    "wave_arm": "call-for-help wave arm x3 + wave hands x3 sheet (see pieces/)",
    "slide_poses": "full-body slide / land / cheer pose sheet (see pieces/)",
    "skin_grandma": "skin: grandma + ginger cat on her shoulder (registered full-figure costume edit)",
    "skin_twins": "skin: twins, the second rides piggyback (registered full-figure costume edit)",
    "skin_dad": "skin: dad in a bathrobe (registered full-figure costume edit)",
    "skin_baby": "skin: mum with the baby in a front sling (registered full-figure costume edit)",
    "skin_teen": "skin: teen with headphones (registered full-figure costume edit)",
    "registration.json": "fit per part (scale, translation, score), sheet scales, piece origins",
}


def row(path):
    rel = os.path.relpath(path, HERE)
    b = os.path.getsize(path)
    if path.endswith(".png"):
        im = Image.open(path)
        dims = f"{im.width}x{im.height} {im.mode}"
    else:
        dims = "json"
    key = os.path.splitext(os.path.basename(path))[0]
    if key.startswith("master_"):
        key = "master"
    d = DESC.get(key) or DESC.get(os.path.basename(path), "")
    return f"| `{rel}` | {dims} | {b // 1024} KB | {d} |"


def main():
    out = ["# Rig parts inventory (generated by make_inventory.py)", "",
           "Common canvas 1024x1536 RGBA for every registered file; see REGISTRATION.md. Pieces under `pieces/` are "
           "trimmed cut-outs from the sheets at SHEET scale: multiply by the rig's `sheet_scale_to_canvas` "
           "(registration.json) to match the canvas.", ""]
    for rig in RIGS:
        d = os.path.join(HERE, rig)
        if not os.path.isdir(d):
            continue
        reg = json.load(open(os.path.join(d, "registration.json")))
        out += [f"## {rig}", "", "| File | Pixels | Bytes | What it is |", "|---|---|---|---|"]
        for f in sorted(os.listdir(d)):
            p = os.path.join(d, f)
            if os.path.isfile(p):
                out.append(row(p))
        pd = os.path.join(d, "pieces")
        if os.path.isdir(pd):
            out += ["", f"Pieces ({rig}/pieces/):", "", "| Piece | Pixels | From sheet | Scale to canvas |", "|---|---|---|---|"]
            owner = {}
            for sh, v in reg.get("pieces", {}).items():
                for nm, pv in v["pieces"].items():
                    owner[nm] = (sh, pv.get("scale_to_canvas"))
            for f in sorted(os.listdir(pd)):
                im = Image.open(os.path.join(pd, f))
                nm = os.path.splitext(f)[0]
                sh, sc = owner.get(nm, ("?", None))
                out.append(f"| `{nm}` | {im.width}x{im.height} | {sh} | {sc if sc else 'size by eye'} |")
        out.append("")
    open(os.path.join(HERE, "INVENTORY.md"), "w").write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
