#!/usr/bin/env python3
"""Derive the LOD texture set (H-06): static/assets/<path> -> static/assets/lod/<path> at LOD_SCALE, and regenerate
src/game/lod.generated.ts (LOD_SCALE + the sorted set of files actually written) so game/assets.ts / assetsScene.ts
can select the LOD path when the static quality tier is not 'high'.

Only the big presentation plates are derived: the environment plates, the win-rung signs, the max-win cards, the
splash feature cards and the Inferno buy card. Facades, board frame, cells and symbols carry pixel meta or are
lossless masters and are NOT in the list.

Each source is resized in premultiplied space (RGBa -> LANCZOS -> RGBA; alpha kept) and written as WebP: lossless
when the source WebP is lossless (VP8L), q90 otherwise. Sources are never modified. Re-run after any of them is
regenerated (tools/art/*).

    python3 tools/perf/derive_lod_textures.py
"""
from __future__ import annotations

import os
import struct
import sys

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
APP = os.path.join(ROOT, "apps", "piggy_firefighters")
ASSETS = os.path.join(APP, "static", "assets")
OUT = os.path.join(ASSETS, "lod")
GENERATED = os.path.join(APP, "src", "game", "lod.generated.ts")

LOD_SCALE = 0.625
LOSSY_QUALITY = 90

LOD_FILES = [
    *(f"environment/{scene}_{orient}.webp" for scene in ("base", "backdraft", "rescue", "inferno") for orient in ("landscape", "portrait")),
    *(f"winrungs/signs/{tier}.webp" for tier in ("big", "huge", "mega", "epic", "max")),
    "maxwin/max_win_card_16x9.webp",
    "maxwin/max_win_card_portrait.webp",
    "splash/card_rescue.webp",
    "splash/card_backdraft.webp",
    "splash/card_alarm.webp",
    "buycards/inferno.webp",
]


def webp_is_lossless(path: str) -> bool:
    """Walk the RIFF chunks: a VP8L bitstream is lossless, VP8 is lossy (VP8X wraps either)."""
    with open(path, "rb") as fh:
        data = fh.read()
    assert data[:4] == b"RIFF" and data[8:12] == b"WEBP", path
    pos = 12
    while pos + 8 <= len(data):
        fourcc = data[pos : pos + 4]
        size = struct.unpack("<I", data[pos + 4 : pos + 8])[0]
        if fourcc == b"VP8L":
            return True
        if fourcc == b"VP8 ":
            return False
        pos += 8 + size + (size & 1)
    raise ValueError(f"no VP8/VP8L chunk in {path}")


def resize_premultiplied(img: Image.Image, scale: float) -> Image.Image:
    w, h = img.size
    size = (max(1, round(w * scale)), max(1, round(h * scale)))
    if img.mode == "RGBA":
        return img.convert("RGBa").resize(size, Image.LANCZOS).convert("RGBA")
    return img.convert("RGB").resize(size, Image.LANCZOS)


def derive(rel: str) -> tuple[int, int, str, tuple[int, int]]:
    src = os.path.join(ASSETS, rel)
    dst = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    lossless = webp_is_lossless(src)
    with Image.open(src) as im:
        has_alpha = im.mode in ("RGBA", "LA", "P") and ("transparency" in im.info or im.mode in ("RGBA", "LA"))
        img = im.convert("RGBA" if has_alpha else "RGB")
    small = resize_premultiplied(img, LOD_SCALE)
    if lossless:
        small.save(dst, "WEBP", lossless=True, exact=True, method=6)
        mode = "lossless"
    else:
        small.save(dst, "WEBP", quality=LOSSY_QUALITY, method=6)
        mode = f"q{LOSSY_QUALITY}"
    return os.path.getsize(src), os.path.getsize(dst), mode + ("+alpha" if has_alpha else ""), small.size


def write_generated(files: list[str]) -> None:
    body = "\n".join(f"\t'{f}'," for f in sorted(files))
    text = (
        "// GENERATED by tools/perf/derive_lod_textures.py — do not edit by hand.\n"
        "// Files under static/assets/lod/<path> exist at LOD_SCALE of the original static/assets/<path>.\n"
        f"export const LOD_SCALE = {LOD_SCALE};\n"
        "export const LOD_FILES: ReadonlySet<string> = new Set([\n"
        f"{body}\n"
        "]);\n"
    )
    with open(GENERATED, "w", encoding="utf-8") as fh:
        fh.write(text)


def main() -> int:
    written = []
    total_src = total_dst = 0
    for rel in LOD_FILES:
        src_b, dst_b, mode, size = derive(rel)
        written.append(rel)
        total_src += src_b
        total_dst += dst_b
        print(f"{rel:<40} {mode:<14} {size[0]}x{size[1]:<5} {src_b:>8,} -> {dst_b:>8,} ({dst_b / src_b - 1:+.0%})")
    write_generated(written)
    print(f"TOTAL {len(written)} files {total_src:,} -> {total_dst:,} ({total_dst / total_src - 1:+.0%}); wrote {os.path.relpath(GENERATED, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
