#!/usr/bin/env node
/**
 * The art lane's meta JSON (written beside the delivered art by tools/art/derive_*.py) -> one typed module the frontend
 * imports: apps/piggy_firefighters/src/game/artMeta.generated.ts.
 *
 * Vite refuses to import a file under static/ (the public dir) as a module, so the geometry the components need
 * (frame opening, cell-frame holes, room boxes, prop sizes, sign planks, the max-win title area, the WILD badge rects) is
 * copied into src by THIS script and gate-checked (`--check`: exit 1 when the committed module differs from what the
 * JSON says). Only the fields the runtime reads are copied; the JSON files stay the art lane's source of truth.
 *
 *   node tools/art/gen_art_meta.mjs            # write
 *   node tools/art/gen_art_meta.mjs --check    # qa/gate: the module matches the served JSON
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('../..', import.meta.url).pathname;
const ASSETS = join(ROOT, 'apps/piggy_firefighters/static/assets');
const OUT = join(ROOT, 'apps/piggy_firefighters/src/game/artMeta.generated.ts');
const read = (rel) => JSON.parse(readFileSync(join(ASSETS, rel), 'utf8'));

const frame = read('ui_scene/frame.meta.json');
const cells = read('ui_scene/cells.meta.json');
const rooms = read('features/rescue/rooms.meta.json');
const props = read('features/rescue/props.meta.json');
const signs = read('winrungs/signs/flat_manifest.json');
const maxwin = read('maxwin/manifest.json');
const symbols = read('sprites/symbolsCartoon/manifest.json');
const symbolsTall = read('sprites/symbolsCartoonTall/manifest.json');

const pick = (obj, keys) => Object.fromEntries(keys.filter((k) => k in obj).map((k) => [k, obj[k]]));
const data = {
	frameMeta: pick(frame, ['w', 'h', 'open_px', 'top_tile', 'rail_period_px']),
	cellsMeta: {
		frames: Object.fromEntries(Object.entries(cells.frames).map(([k, v]) => [k, pick(v, ['file', 'size', 'hole'])])),
		line_plate: pick(cells.line_plate, ['file', 'size']),
	},
	roomsMeta: {
		states: rooms.states,
		facade: rooms.facade,
		pitch_px: rooms.pitch_px,
		rooms: rooms.rooms.map((r) => pick(r, ['reel', 'size', 'box_in_facade', 'window_in_facade', 'files'])),
	},
	propsMeta: { props: Object.fromEntries(Object.entries(props.props).map(([k, v]) => [k, pick(v, ['file', 'size', 'rung_period_px', 'rail_span_px'])])) },
	signsMeta: Object.fromEntries(Object.entries(signs).map(([k, v]) => [k, pick(v, ['file', 'w', 'h', 'plank', 'board', 'title_centre'])])),
	maxwinMeta: pick(maxwin, ['files', 'size', 'titleSafeArea']),
	symbolsMeta: pick(symbols, ['tile', 'pad', 'wild_badge']),
	symbolsTallMeta: pick(symbolsTall, ['tile', 'fill_w', 'wild_badge']),
};

const header = `/**
 * GENERATED by tools/art/gen_art_meta.mjs from the art lane's meta JSON under static/assets (frame.meta.json,
 * cells.meta.json, rooms.meta.json, props.meta.json, winrungs/signs/flat_manifest.json, maxwin/manifest.json, the two
 * symbol manifests). Do not edit: re-run the script after a derive tool changes a rect; qa/gate checks it is in sync.
 * game/artMeta.ts is the typed reader.
 */
`;
const body = Object.entries(data)
	.map(([name, value]) => `export const ${name} = ${JSON.stringify(value, null, '\t')} as const;\n`)
	.join('\n');
const next = header + body;

if (process.argv.includes('--check')) {
	let current = '';
	try {
		current = readFileSync(OUT, 'utf8');
	} catch {
		/* missing */
	}
	if (current !== next) {
		console.error('FAIL gen_art_meta: apps/piggy_firefighters/src/game/artMeta.generated.ts is out of date (run node tools/art/gen_art_meta.mjs)');
		process.exit(1);
	}
	console.log('OK gen_art_meta: artMeta.generated.ts matches the served meta JSON');
} else {
	writeFileSync(OUT, next);
	console.log('wrote', OUT, `${next.length} bytes`);
}
